### PR TITLE
updating xmlrpc to Python3 and added RPC2 suffix to RPC call

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by ocramz** [comment]
I noticed the RPC2 suffix here : http://www.pymolwiki.org/index.php/XML-RPC_server

**Comment by ocramz** [comment]
Latest commit addresses #5

**Comment by cxhernandez** [comment]
Hey @ocramz! Thanks for the PR, however I would have imagined that the [`2to3`](https://github.com/cxhernandez/ipymol/blob/master/setup.py#L28) flag in `setup.py` would take care of this. Do you find that it's not working? I'd like to keep backwards compatibility with py2 for the time being, if possible.

**Comment by cxhernandez** [comment]
Also, nice find with the `RPC2` suffix! That'd be very useful

**Comment by ocramz** [comment]
Hi @cxhernandez , I was repeatedly getting a Connection refused from PyMol. This PR is a total kludge but I found it to be working against the latest PyMol (1.8.2.0) and with Python 3.4, and I'm using it in https://github.com/ocramz/jupyter-docker-pymol

**Pull request closed without merging**
